version: '2'
services:
    sample-app:
        image: sample
        external_links:
            - sample-mysql:mysql
            - sample-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/SpringStarterDb?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    sample-mysql:
        extends:
            file: mysql.yml
            service: sample-mysql
    sample-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: sample-elasticsearch
