version: '2'
services:
    sample-mysql:
        container_name: sample-mysql
        image: mysql:5.7.13
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=sample
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=2 --skip-ssl
